version: 2
_rsync: 
  rsync_install: &rsync_install
    name: Install rsync
    command: sudo apt install -y rsync
_build:
  build_container: &build_container
    name: Build container
    command: |
      docker build -t imagen .
      mkdir /tmp/artifacts
      echo "imagen" >> /tmp/artifacts/artifactory_tag
jobs:
  install_deps:
    working_directory: ~/circleCI
    docker:
      - image: circleci/node:erbium
    steps:
      - checkout
      - attach_workspace:
          at: ~/circleCI
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: .
          paths: .
  build:
    working_directory: ~/circleCI
    docker:
      - image: circleci/node:erbium
    steps:
      - checkout
      - attach_workspace:
          at: ~/circleCI
      - run: *rsync_install
      - run:
          name: Build
          command: yarn build
      - run:
          name: Copy to a folder
          command: yarn cpBuild
      - save_cache:
          key: node_modules-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
          command: yarn build
      - save_cache:
          key: build-cache-{{ .Revision }}
          paths:
            - build
  build-and-upload-image:
    working_directory: ~/circleCI
    docker:
       - image: circleci/node:erbium
    steps:
      - checkout
      - restore_cache:
          key: build-cache-{{ .Revision }}
      - attach_workspace:
          at: workspace
      - run: 
          name: Echo structure
          command: ls -la
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - install_deps
      - build:
          requires:
            - install_deps
      - build-and-upload-image:
          requires:
            - build
